package sugar

type ServiceGroup struct {
	SugarTeamsService
	SugarTeamMembersService
	SugarDbConnectionsService
	SugarSemanticModelsService
	SugarAgentsService
	SugarCityPermissionsService
	SugarRowLevelOverridesService
	SugarExecutionLogsService
	SugarWorkspacesService
	SugarFormulaQueryService
	SugarFoldersService
}
